server:
  port: 7002
logging:
  level:
    root: INFO
    co.istad.api: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
spring.data.mongodb:
  host: localhost
  port: 27017
  database: product-db
