spring:
  data:
    mongodb:
      host: mongodb
  config:
    activate:
      on-profile: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka
  rabbitmq:
    host: rabbitmq
server:
  port: 8080