server:
  port: 7003
  error:
    include-message: always
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost/review-db
    username: devkh
    password: devKH@10
    hikari:
      initialization-fail-timeout: 60000
  cloud:
    function:
      definition: messageProcessor
    stream:
      default-binder: rabbit
      default:
        contentType: application/json
      bindings:
        messageProcessor-in-0:
          destination: reviews
          group: reviewsGroup
          consumer:
            max-attempts: 3
            back-off-initial-interval: 500
            back-off-max-interval: 1000
            back-off-multiplier: 2.0
      rabbit:
        bindings:
          messageProcessor-in-0:
            consumer:
              auto-bind-dlq: true
              republish-to-dlq: true
      kafka:
        bindings:
          messageProcessor-in-0:
            consumer:
              enable-dlq: true
        binder:
          brokers: 127.0.0.1
          defaultBrokerPort: 9092
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

logging:
  level:
    root: INFO
    co.istad: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
