version: '3'

services:
  product:
    build: microservices/product-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mongodb:
        condition: service_healthy

  recommendation:
    build: microservices/recommendation-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mongodb:
        condition: service_healthy

  review:
    build: microservices/review-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      postgresql:
        condition: service_healthy

  product-composite:
    build: microservices/product-composite-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  mongodb:
    image: mongo:7.0.6
    ports:
      - "27017:27017"
    command: mongod
    healthcheck:
      test: "mongostat -n 1"
      interval: 5s
      timeout: 2s
      retries: 60

  postgresql:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=review-db
      - POSTGRES_USER=devkh
      - POSTGRES_PASSWORD=devKH@10
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "devkh", "-d", "review-db"]
      interval: 20s  # Check every 20 seconds
      timeout: 3s     # Wait up to 3 seconds for successful check
      retries: 5     # Retry up to 5 times before marking unhealthy
